crud/urls.py
from django.contrib import admin
from django.urls import path, include
from first import urls as first_urls
from products import urls as products_urls
from products.views import list
from django.conf import settings #image 업로드에 필요
from django.conf.urls.static import static #image 업로드에 필요

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', list, name="list"),
    path('first/', include(first_urls)),
    path('products/', include(products_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

first/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('one/', views.one, name="one"),
    path('two/', views.two, name="two"),
    path('three/', views.three, name="three"),

]

products/urls.py
from django.urls import path
from . import views

app_name = "products" 
urlpatterns = [
    path('create/', views.create, name="create"),
    path('<int:id>/', views.show, name="show"),
    path('edit/<int:id>/', views.edit, name="edit"),
    #path('show/<int:id>/', views.show, name="show"), 이렇게 주소를 간력화 할 수 있음
    path('update/<int:id>/', views.update, name="update"),
    path('delete/<int:id>/', views.delete, name="delete"),
]

#앱을 여러개 만들면 create라는 html을 여러개 만들게 될텐데. app_name을 설정하면 products:create라고 써야해서 create.html여러개 만들어도 구분할 수 있음
#id라는 이름으로, integer라는 타입으로 주소를 전달한다
#int 타입인 id를 views에서 받을 수 있어야 함

first/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(null=True) #빈 값도 참으로 인식함
    price = models.IntegerField()
    view_count = models.IntegerField(default=0) #default값을 설정해야함
    image = models.ImageField(upload_to="images/", null=True) #pip install pillow

    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.title
    #title을 제목으로 받게 해주는 함수

first/views.py
from django.shortcuts import render

# Create your views here.

def one(request):
    return render(request, 'first/one.html')


def two(request):
    return render(request, 'first/two.html')


def three(request):
    return render(request, 'first/three.html')

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product
import pdb #pyhton debuging

# Create your views here.

def list(request):
    products = Product.objects.all() #model의 Products에서 모든 것을 받아 온다. 그리고 products라는 변수에 담는다
    return render(request, 'products/list.html', {'products': products}) #3번째 key값으로 dictionary 타입


def create(request):
    if request.method == "POST":
        title = request.POST.get('title')
        price = request.POST.get('price')
        description = request.POST.get('description')
        # product = Product(title=title, price=price, description=description)
        # product.save()
        # pdb.set_trace() #여기서 멈춰서 python 디버깅 실시
        image = request.FILES.get('image') #POST가 아니라 FILES로 받아야함
        product = Product.objects.create(title=title, price=price, description=description, image=image)
        return redirect('list')
    return render(request, 'products/create.html')


def show(request, id):
    # product = Product.objects.get(pk=id)
    product = get_object_or_404(Product, pk=id)
    default_view_count = product.view_count
    product.view_count = default_view_count +1
    product.save()
    return render(request, 'products/show.html', {'product': product})
    #object를 가져와서 3번째 인자로 show에 넘긴다
    #각 상품마다의 pk로 구분
    #2를 이용해서 Product에서 pk(id)가 2인 녀석을 찾아서 show.html로 넘긴다
    #주소로 pk값을 넘긴다


def edit(request, id):  #edit 역시 특정 상품의 id를 받아올 수 있어야 한다
    # product = Product.objects.get(pk=id)
    product = get_object_or_404(Product, pk=id)
    return render(request, 'products/edit.html', {'product': product})


def update(request, id):
    if request.method == "POST":
        # product = Product.objects.get(pk=id)
        product = get_object_or_404(Product, pk=id)
        title = request.POST.get('title')
        price = request.POST.get('price')
        description = request.POST.get('description')
        product.title = title
        product.price = price
        product.description = description
        product.save()
        return redirect('products:show', product.pk)


#create와 비슷하나 edit과 update로 나눴다
#edit은 POST방식이니 if문이 들어감 (create와 비슷)


def delete(request, id):
    if request.method == "POST":
        # product = Product.objects.get(pk=id)
        product = get_object_or_404(Product, pk=id)
        product.delete()
        return redirect('list')

first/templates/first/one.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>one.html 입니다</h1>
<img src="{% static 'image/baby_lion.jpg' %}" alt="baby_lion" class="baby_lion">
<a href="{% url 'two' %}">two</a>

{% endblock %}

first/templates/first/three.html
{% extends 'base.html' %}

{% block content %}

<h1>three.html 입니다</h1>
<a href="{% url 'one' %}">one</a>

{% endblock %}

first/templates/first/two.html
{% extends 'base.html' %}

{% block content %}

<h1>two.html 입니다</h1>
<a href="{% url 'three' %}">three</a>

{% endblock %}

products/templates/products/create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>create.html 입니다</h1>

<form action="{% url 'products:create' %}" method="POST" enctype="multipart/form-data"> <!--media 받을 땐 enctype 써야함-->
    {% csrf_token %}
    <label>상품이름</label><br>
    <input type="text" name="title"><br><br>

    <label>가격</label><br>
    <input type="number" name="price"><br><br>

    <label>상품 이미지</label><br>
    <input type="file" name="image"><br><br>

    <label>상품 설명</label><br>
    <textarea cols="30" rows="10" name="description"></textarea><br><br>

    <input type="submit" class="btn btn-secondary" value="등록">
</form>


{% endblock %}

products/templates/products/edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>상품정보 수정</h1>

<form action="{% url 'products:update' product.pk %}" method="POST" enctype="multipart/form-data"> <!--객체의 id 넘겨줘야함-->
    {% csrf_token %}
    <label>상품이름</label><br>
    <input type="text" name="title" value="{{ product.title }}"><br><br>

    <label>가격</label><br>
    <input type="number" name="price" value="{{ product.price }}"><br><br>

    <label>상품 이미지</label><br>
    <input type="file" name="image"><br><br>

    <label>상품 설명</label><br>
    <textarea cols="30" rows="10" name="description">{{ product.description }}</textarea><br><br>

    <input type="submit" class="btn btn-secondary" value="수정">
</form>
<!--form안에 pk로 받은 값을 띄우려면 value로 views에서 product = Product.objects.get(pk=id)로 받은 값을 가져오면 됨-->

{% endblock %}

products/templates/products/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <!--html에서 변수를 쓰려면 views에서 3번쨰 인자로 dictionary 타입으로 모든 인자를 받아야 함-->
    <!--각각의 인자로 쪼개서 반복문 써서 모든 인자에 카드를 씌워야 함-->

    <div class="row">
        {% for item in products %} <!--products는 views에서 3번째 key값으로 던져준 값. 이걸 items로 쪼갬-->
        
        <!-- <div class="card col-4" style="width: 18rem;"> 
            <div class="card-body">
                <h5 class="card-title">{{ item.title }}</h5>
                <h3 class="card-subtitle">{{ item.price }} 원</h3>
                <p class="card-text">{{ item.description }}</p>
                <a href="{% url 'products:show' item.pk %}" class="btn btn-secondary">상세 보기</a>
            </div>
        </div> -->
    
        <div class="card col-4" style="width: 18rem;"><!--col이 총 12 사이즈인데 col-4로 4로 나눴으므로 전체 3개씩 뜨게 됨-->
            {% if item.image %} <!--조건문 써야 image없어도 에러 안뜸-->
                <img src="{{ item.image.url }}" class="card-img-top" alt="...">
            {% endif %}
            <div class="card-body">
                <h3 class="card-title">{{ item.title }}</h3>
                <h5 class="card-subtitle">{{ item.price }} 원</h5>
                <p class="card-text">{{ item.description }}</p>
                <a href="{% url 'products:show' item.pk %}" class="btn btn-secondary">상세 보기</a>
                <!--디버깅: ' products:show' 스페이스 한칸도 에러 뜸-->
            </div>
        </div>

        {% endfor %}
    </div>
{% endblock %}

products/templates/products/show.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>상품 상세 보기 페이지 - show.html</h1><br>
<h2>상품 이름 : {{ product.title }}</h2><br>
<h4>상품 가격 : {{ product.price }}</h4><br>
<h5>조회수 : {{ product.view_count }}</h5>
<p>설명 : {{ product.description }}</p><br><br>

<a href="{% url 'products:edit' product.pk %}" class="btn btn-secondary">수정</a>
    <!--edit은 pk값을 넘겨받아야함(views에서 그렇게 설정함). 그래서 product.pk를 써야함-->
<a href="#" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModal">삭제</a>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">삭제하시겠습니까?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">취소</button>
                <!--<a href="{% url 'products:delete' product.pk %}" class="btn btn-primary">삭제</button>-->
                <!--a 태그는 삭제 노노. POST 방식을 써야 하므로 form을 쓴다-->
                <form action="{% url 'products:delete' product.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="삭제" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/project.css' %}">
    <title>CRUD</title>
</head>

<body>

    <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'list' %}">list.html로 이동</a>
                    <a class="nav-link" href="{% url 'products:create' %}">create.html로 이동</a>
                </li>
            </ul>
        </div>
    </nav> -->

    {% include 'navbar.html' %}

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>

    {% include 'footer.html' %}

    <!-- <footer class="page-footer font-small blue">

        <div class="footer-copyright text-center py-3">© 2019 Copyright: 김재형
            <a href="https://dongguk.likelion.org">dongguk.likelion.org</a>
        </div>

    </footer> -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

templates/footer.html
<!-- Footer -->
<footer class="page-footer font-small blue">

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright: 김재형
        <a href="https://dongguk.likelion.org">dongguk.likelion.org</a>
    </div>
    <!-- Copyright -->

</footer>
<!-- Footer -->

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'list' %}">list.html로 이동</a>
                <a class="nav-link" href="{% url 'products:create' %}">create.html로 이동</a>
            </li>
        </ul>
    </div>
</nav>